feat: Support modifying responses before caching
kellnerd/snap_storage pull request #1
Opened 2024-04-19 12:36 UTC by atj

This commit adds support for passing a mutator function as an argument to cache. The primary use case is making requests to non-API URLs where the response may contain large amounts of dynamic and/or superflous data.

2024-04-19 12:40 UTC, atj commented on src/snap_storage.test.ts
> +    const testFile = "test_data/mutator.json";
I wasn't sure what else to do here as `deno.json` is already cached by the previous test.

2024-04-19 13:12 UTC, kellnerd requested changes
Thank you, this is going to be a very versatile feature despite its simple implementation!

2024-04-19 13:12 UTC, kellnerd commented on src/snap_storage.test.ts
> +    const testFile = "test_data/mutator.json";
Glad that you mentioned this caveat, I was just about to ask why you haven't simply reused the existing file.
Since the content does not really matter for this test, you could also fetch the README and turn it into a totally independent response, I guess.

2024-04-19 13:12 UTC, kellnerd commented on src/snap_storage.test.ts
> +    assert(!storedSnap.isFresh, "Existing snapshots should not be fresh");
```suggestion
    const fetchedJSON = await fetchedSnap.content.json();

    assert(fetchedJSON.mutation, "JSON response was not mutated");
```
You can remove the last three assertions, they should already be covered by the previous test case.

2024-04-19 13:12 UTC, kellnerd commented on src/snap_storage.ts
>    ): Promise<Snapshot<Response>> {
```ts
  async cache(url: string | URL, {
    fetch = self.fetch,
    requestInit,
    responseMutator,
    policy = {},
  }: CacheOptions = {}): Promise<Snapshot<Response>> {
```
feels more readable to me than the formatter's suggestion.

2024-04-19 13:12 UTC, kellnerd commented on src/snapshot.ts
> +export type ResponseMutator = (response: Response) => Promise<Response>;
Please move this type definition into the other module where it is used.
It would also make sense to add a JSDoc comment to it and re-export it from mod.ts as it is part of the public API.

2024-04-19 15:28 UTC, atj commented on src/snapshot.ts
> +export type ResponseMutator = (response: Response) => Promise<Response>;
Done. Hopefully the comment is OK. I added a note to point out that the returned Response body must not have been used, as I think it's easy to overlook.

How do you feel about adding a check that throws if `response.bodyUsed` is true?

2024-04-19 15:30 UTC, atj commented on src/snap_storage.ts
>    ): Promise<Snapshot<Response>> {
Deno's formatter didn't like that, so I ended up with the following which I think is readable:

```javascript
  async cache(
    url: string | URL,
    {
      fetch = self.fetch,
      requestInit,
      responseMutator,
      policy = {},
    }: CacheOptions = {},
  ): Promise<Snapshot<Response>> {
```

2024-04-19 15:30 UTC, atj commented
Thanks for the suggestions, I've updated the PR and added a couple of comments.

2024-04-20 09:08 UTC, kellnerd commented on src/snap_storage.ts
>    ): Promise<Snapshot<Response>> {
Strange, I had Deno 1.41.3 installed which accepted both variants. After upgrading to 1.42.4 both variants were still accepted.
However, your variant is probably even more readable, so let's just use that.

2024-04-20 09:30 UTC, kellnerd commented on src/snapshot.ts
> +export type ResponseMutator = (response: Response) => Promise<Response>;
Your comment is good, also the idea with the note about the response body.
I was also bitten by that behaviour as you can see by two out of four inline comments explaining the duplication of a `ReadableStream` ;)

A quick test to see what happens if `responseMutator` returns an already consumed response reveals that this is already throwing by default:
```
error: TypeError: Body is unusable.
        snap = await this.createSnap(url, response.clone().body!, {
```
So unless you want to have a more specific error message, I think this is sufficient to catch developer mistakes.

2024-04-20 09:35 UTC, kellnerd requested changes
Looking very good now, except for two minor stylistic issues.
My code spell checker found a typo in your commit message which I had also missed while reviewing: superfluous

2024-04-20 09:35 UTC, kellnerd commented on mod.ts
> +export { type CacheOptions, type ResponseMutator, SnapStorage } from "./src/snap_storage.ts";
The line became to long, linter is complaining.

2024-04-20 10:13 UTC, atj commented
Hopefully everything is resolved now. Thanks for you patience!

2024-04-20 10:18 UTC, kellnerd approved these changes

2024-04-20 10:18 UTC, merged

2024-04-20 10:25 UTC, kellnerd commented
Released as v0.6.0, [documentation](https://deno.land/x/snap_storage@v0.6.0?doc) is looking good!